In [132]:
#import librabries
import numpy as np
import pandas as pd

In [19]:
# Assuming your dataset is stored in a DataFrame named 'df

In [133]:
df= pd.read_csv("Data-cleaning-for-beginners-using-pandas.csv")
print(df)
print(type(df))

    Index   Age      Salary  Rating       Location  Established Easy Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3  64.0   $44k-$99k     4.4       India In         1988         -1
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009         -1
12     12   NaN   $44k-$99k     0.0       India,In         1999         -1
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16     16  19.0   $19k-$40k     4.5       India,In         1984         -1
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22     22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0   $44k-$99k     5.4       India,In         1935         -1
28     28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1
<class 'pandas.core.frame.DataFrame'>

In [134]:
df_frame = df.copy()

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [136]:
df.isna().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [137]:
df.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [138]:
df.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [140]:
df.shape

(29, 7)

In [139]:
df.columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

In [102]:
# Question 1: Missing Values
missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [103]:
# Question 2: Data Types
data_types = df.dtypes
print("\nData Types:")
print(data_types)

Data Types:
Index            int64
Age            float64
Salary          object
Rating         float64
Location        object
Established      int64
Easy Apply      object
dtype: object

In [104]:
# Question 3: Outliers
# You can use descriptive statistics to identify potential outliers
outliers = df[['Age', 'Salary', 'Rating']].describe(percentiles=[0.25, 0.75])
print("\nOutliers:")
print(outliers)

Outliers:
             Age     Rating
count  22.000000  28.000000
mean   39.045455   3.528571
std    16.134781   2.825133
min    13.000000  -1.000000
25%    25.000000   1.050000
50%    39.500000   4.200000
75%    50.000000   5.400000
max    66.000000   7.800000

In [157]:
# Question 4: Salary Formatting
# Assuming Salary column needs formatting, e.g., removing '$' and converting to numeric
df['Salary'].value_counts()

$44k-$99k     19
$55k-$66k      3
$77k-$89k      2
$10k-$49k      2
$88k-$101k     1
$19k-$40k      1
$39k-$88k      1
Name: Salary, dtype: int64

In [158]:
df['Salary'] = df['Salary'].str.replace('$', '').str.replace('k', '000')

<ipython-input-158-ae8039f37475>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Salary'] = df['Salary'].str.replace('$', '').str.replace('k', '000')

In [159]:
df['Salary'] = df['Salary'].str.replace('-', ' ').str.split(' ').apply(lambda x: (float(x[0]) + float(x[1])) / 2)

In [108]:
df.head()

   Index   Age   Salary  Rating       Location  Established Easy Apply
0      0  44.0  71500.0     5.4       India,In         1999       TRUE
1      1  66.0  60500.0     3.5    New York,Ny         2002       TRUE
2      2   NaN  83000.0    -1.0    New York,Ny           -1         -1
3      3  64.0  71500.0     4.4       India In         1988         -1
4      4  25.0  71500.0     6.4  Australia Aus         2002         -1

In [142]:
df['Location']

0          India,In
1       New York,Ny
2       New York,Ny
3          India In
4     Australia Aus
5          India,In
6       New York,Ny
7     Australia Aus
8       New York,Ny
9          India,In
10         India,In
11         India,In
12         India,In
13    Australia Aus
14    Australia Aus
15    Australia Aus
16         India,In
17      New York,Ny
18      New York,Ny
19      New York,Ny
20      New York,Ny
21      New York,Ny
22      New York,Ny
23      New York,Ny
24      New York,Ny
25    Australia Aus
26         India,In
27         India,In
28    Australia Aus
Name: Location, dtype: object

In [143]:
# Question 5: Location Standardization
# Standardizing location entries by removing special characters
df['Location'] = df['Location'].replace({'New York,Ny':'New York', 'India,In':'India','India In':'India', 'Australia Aus':'Australia'})

In [144]:
df['Location'] = df['Location'].replace(r'\sIn$', '')

In [125]:
l = ['India','In']
l[1]

'In'

In [145]:
df['Location'].str.split(",",expand=True)[0]

0         India
1      New York
2      New York
3         India
4     Australia
5         India
6      New York
7     Australia
8      New York
9         India
10        India
11        India
12        India
13    Australia
14    Australia
15    Australia
16        India
17     New York
18     New York
19     New York
20     New York
21     New York
22     New York
23     New York
24     New York
25    Australia
26        India
27        India
28    Australia
Name: 0, dtype: object

In [160]:
df.head()

   Index   Age   Salary  Rating   Location  Established  Easy Apply
0      0  44.0  71500.0     5.4      India       1999.0        True
1      1  66.0  60500.0     3.5    NewYork       2002.0        True
2      2   NaN  83000.0    -1.0    NewYork          NaN        True
3      3  64.0  71500.0     4.4      India       1988.0        True
4      4  25.0  71500.0     6.4  Australia       2002.0        True

In [165]:
# Question 6: Established Column
# Handling inconsistencies in the Established column, replacing -1 with 1999
df['Established'] = df['Established'].replace(-1,1999)

In [149]:
# Question 7: Easy Apply Indicator
# Assuming Easy Apply contains boolean values, you can convert it to boolean type
df['Easy Apply'] = df['Easy Apply'].astype(bool)

In [150]:
# Question 9: Age Distribution
# Checking the distribution of Age column
age_distribution = df['Age'].value_counts()
print("\nAge Distribution:")
print(age_distribution)

Age Distribution:
44.0    5
35.0    3
66.0    2
25.0    2
55.0    2
19.0    2
64.0    1
21.0    1
22.0    1
32.0    1
13.0    1
52.0    1
Name: Age, dtype: int64

In [151]:
# Question 10: Handling Special Characters
# Checking for special characters in text-based columns
# Assuming Location is the only relevant text-based column
df['Location'] = df['Location'].str.replace('[^a-zA-Z,]', '')
# this was answer to previous question of location

<ipython-input-151-e1e3c92ccd84>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Location'] = df['Location'].str.replace('[^a-zA-Z,]', '')

In [152]:
# Question 11: Data Integrity
# Checking if Established column aligns with Age column
# You may want to define specific rules based on your data
# For example, ensuring Established is not greater than the current year
df['Established'] = np.where(df['Established'] > pd.to_datetime('today').year, np.nan, df['Established'])

In [ ]:
# Question 12: Easy Apply Transformation
# If Easy Apply column contains non-boolean values, you can transform it into a boolean
# This step is already done in Question 7

In [ ]:
# Question 13: Location Accuracy
# Assessing the accuracy of location entries
#  a reference dataset to check for misspelled or ambiguous locations

In [ ]:
# Question 14: Handling Categorical Data
# Encoding or transforming categorical indicators (if any) for analysis
# No specific categorical columns are mentioned in the provided dataset

In [ ]:
# Question 15: Consistent Rating Scale
# Ensuring a consistent rating scale (normalization or adjustment)
# No specific instructions provided, you may want to define your criteria

In [163]:
df.head()

   Index   Age   Salary  Rating   Location  Established  Easy Apply
0      0  44.0  71500.0     5.4      India       1999.0        True
1      1  66.0  60500.0     3.5    NewYork       2002.0        True
2      2   NaN  83000.0    -1.0    NewYork          NaN        True
3      3  64.0  71500.0     4.4      India       1988.0        True
4      4  25.0  71500.0     6.4  Australia       2002.0        True